[workspace]
members = ["day-*"]
resolver = "2"

[workspace.dependencies]
dhat = "0.3.2"
itertools = "0.12.0"
lazy_static = "1.4.0"
nom = "7.1.3"
nom-regex = "0.2.0"
rayon = "1.8.0"
regex = "1.10.2"

# dev
pretty_assertions = "1.4.0"

[profile.release]
debug = 1
