repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: just-check-and-test-all-2022
        name: just check-and-test-all (2022)
        entry: bash -ic "cd 2022 && just check-and-test-all"
        language: system
        types: [rust]
        files: ^2022/.*$
        pass_filenames: false
