repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: just-check-and-test
        name: just check-and-test
        entry: just check-and-test
        language: system
        types: [rust]
        files: ^20\d\d/.*$
        pass_filenames: true
      - id: fmt
        name: fmt
        entry: just fmt
        language: system
        types: [rust]
        files: ^20\d\d/.*$
        pass_filenames: false
