[package]
name = "day-8"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-8"
path = "src/_bin/main.rs"

[dependencies]
dhat = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions.workspace = true

[features]
dhat-heap = ["dep:dhat"]
