[package]
name = "day-1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-1"
path = "src/_bin/main.rs"

[dependencies]
itertools.workspace = true
nom.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
