check-and-test-all:
	for dir in $(fd -t d day); do just _check-and-test $dir; done

_check-and-test dir:
	#!/usr/bin/env bash
	cd {{dir}}
	cargo check
	cargo test
	cargo test --release

copy-scaffolding number="$(date +'%d' | sed 's/^0//')":
	mkdir -p "day-{{number}}"
	cp -r ./scaffolding/rust/* "day-{{number}}"
	fd -e rs -e toml . "day-{{number}}/" -X sd -s "DAYNUM" "{{number}}"
