import "../../justfile"

set allow-duplicate-recipes

_default:
	@just --list

# run `gradle test` from the root of the Kotlin project
test:
	gradle test

# launch IntelliJ IDEA
intellij:
	nix develop .#ide --command idea-community
