import "../../justfile"

set allow-duplicate-recipes := true

_default:
    @just --list

# check the current day
[no-cd]
[group("check")]
check:
    dub test

# check every day this year
[group("check")]
check-year:
    #!/usr/bin/env bash
    rc=0
    for d in {{ source_directory() }}/day*; do
        cd "$d"
        just check
        [ $? -ne 0 ] && rc=1
    done
    exit $rc
